name: Tests

on:
  push:
    paths-ignore:
    - '**.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: |
        npm install
        npm run build

    - name: Run tests
      run: |
        npm install
        npm run test:coverage